name: Replace Variables

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Replace env.js
        run: |
          sed -i "s|'YOUR_OPENROUTER_TITLE'|'${{vars.OPENROUTER_TITLE}}'|g" pages/v1/env.js
          sed -i "s|'YOUR_OPENROUTER_REFERER'|'${{vars.OPENROUTER_REFERER}}'|g" pages/v1/env.js
          
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pages/v1/env.js
          git commit -m "Auto replace strings for deployment" || echo "No changes to commit"
          git push
